import type { IntakeEvent } from "./types";

/**
 * Seeded raw communications for the intake pipeline — service-inbox emails,
 * texts, and calls (transcripts from the phone system). All fictional but
 * shaped like the real day: a high-confidence duplicate pair (Greenleaf),
 * a must-be-named AI ask (Summit), missed calls that must not rot, an
 * unknown caller with no account match, and stale items that show recency
 * decay on the Pending board.
 *
 * Offsets are minutes before seed time; seeding stamps real ISO times once
 * (INSERT OR IGNORE — operator triage survives restarts).
 */
export interface IntakeSeed
  extends Omit<IntakeEvent, "receivedAt" | "status" | "ticketId" | "ackSentAt" | "ackBody"> {
  minutesAgo: number;
}

export const SEED_INTAKE_EVENTS: IntakeSeed[] = [
  {
    id: "in-greenleaf-hoa-1",
    channel: "email",
    fromName: "Priya Patel",
    fromContact: "office@greenleaflandscape.com",
    accountId: "acct-greenleaf",
    minutesAgo: 25,
    subject: "COI for Palm Court HOA — clubhouse contract",
    body: "Hi team — Palm Court HOA needs a certificate for our new clubhouse maintenance contract. They just need to be listed as certificate holder with the usual additional insured wording. Contract starts Monday. Thanks! — Priya",
    callMissed: null,
    callDurationSec: null,
  },
  {
    id: "in-greenleaf-hoa-2",
    channel: "email",
    fromName: "Priya Patel",
    fromContact: "office@greenleaflandscape.com",
    accountId: "acct-greenleaf",
    minutesAgo: 5,
    subject: "Re: COI for Palm Court HOA — clubhouse contract",
    body: "Following up on my email from earlier — same request, Palm Court HOA certificate for the clubhouse contract. Just making sure it didn't get buried. — Priya",
    callMissed: null,
    callDurationSec: null,
  },
  {
    id: "in-summit-gc-named",
    channel: "email",
    fromName: "Dan Kowalski",
    fromContact: "dan@summitdrywall.com",
    accountId: "acct-summit",
    minutesAgo: 120,
    subject: "GC requires named additional insured — Hartline Builders",
    body: "Our new GC, Hartline Builders LLC, reviewed the cert and says blanket wording is not enough — their contract requires being specifically named on the policy by endorsement. Can you get that going with the carrier? Job starts in two weeks.",
    callMissed: null,
    callDurationSec: null,
  },
  {
    id: "in-apex-oak-text",
    channel: "text",
    fromName: "Vince Amato",
    fromContact: "+1 415 555 0421",
    accountId: "acct-apex",
    minutesAgo: 40,
    subject: null,
    body: "Hey its Vince from Apex — need a cert for Oak Street Builders again, new site at 6th and Brannan. Same as last time. Today if possible?",
    callMissed: null,
    callDurationSec: null,
  },
  {
    id: "in-northstar-lender-call",
    channel: "call",
    fromName: "Gloria Mendes",
    fromContact: "+1 510 555 0388",
    accountId: "acct-northstar",
    minutesAgo: 180,
    subject: "Voicemail — lender certificate",
    body: "Transcript (voicemail): Hi, this is Gloria at North Star dispatch. Our equipment lender, Pacific Fleet Capital, needs a certificate showing the garage liability and garagekeepers before they release the two new box trucks. Call me back when you can, thanks.",
    callMissed: true,
    callDurationSec: null,
  },
  {
    id: "in-meridian-event-call",
    channel: "call",
    fromName: "Sofia Reyes",
    fromContact: "+1 415 555 0466",
    accountId: "acct-meridian",
    minutesAgo: 60,
    subject: "Call — venue certificate for Saturday event",
    body: "Transcript: Caller confirmed the Meridian Reach launch event Saturday at The Foundry SF. Venue requires a certificate with the venue named as additional insured on the special events policy, liquor included. Operator confirmed policy numbers on file and promised same-day turnaround.",
    callMissed: false,
    callDurationSec: 372,
  },
  {
    id: "in-craft-venue-email",
    channel: "email",
    fromName: "Lena Brooks",
    fromContact: "events@craftandbarrel.com",
    accountId: "acct-craft",
    minutesAgo: 60 * 26,
    subject: "Certificate for Saturday wedding — Meadowbrook Farm",
    body: "Hello! We're catering a wedding at Meadowbrook Farm next month and the venue wants a certificate with liquor liability shown and the farm listed. Their coordinator said blanket additional insured is fine if the policy carries it.",
    callMissed: null,
    callDurationSec: null,
  },
  {
    id: "in-pixel-client-text",
    channel: "text",
    fromName: "Jae Park",
    fromContact: "+1 628 555 0233",
    accountId: "acct-pixel",
    minutesAgo: 30,
    subject: null,
    body: "Can you send our E&O cert to our new client Brightwave Media? Their vendor portal needs it before they issue the SOW. Email is vendors@brightwavemedia.com",
    callMissed: null,
    callDurationSec: null,
  },
  {
    id: "in-unknown-foodtruck-call",
    channel: "call",
    fromName: "Unknown Caller",
    fromContact: "+1 707 555 0912",
    accountId: null,
    minutesAgo: 50,
    subject: "Voicemail — new business inquiry",
    body: "Transcript (voicemail): Hi, I got your number from a friend — I run a food truck in Santa Rosa and need a quote for liability insurance, maybe the whole package. Name's Marco. Call me back at this number.",
    callMissed: true,
    callDurationSec: null,
  },
  {
    id: "in-harbor-landlord-email",
    channel: "email",
    fromName: "Bayview Property Partners",
    fromContact: "leasing@bayviewpp.com",
    accountId: "acct-harbor",
    minutesAgo: 60 * 24 * 4,
    subject: "Insurance requirement — Suite 210 lease renewal",
    body: "Per the renewal for Suite 210, please provide an updated certificate naming Bayview Property Partners LP as additional insured (managers or lessors of premises) and certificate holder. The prior cert expires with the lease term.",
    callMissed: null,
    callDurationSec: null,
  },
  {
    id: "in-vendor-newsletter",
    channel: "email",
    fromName: "InsurTech Weekly",
    fromContact: "newsletter@insurtechweekly.example",
    accountId: null,
    minutesAgo: 65,
    subject: "5 Trends Reshaping Commercial Lines In 2026",
    body: "You're receiving this because you subscribed to InsurTech Weekly. This week: embedded insurance, AI triage desks, and the death of the fax machine…",
    callMissed: null,
    callDurationSec: null,
  },
  {
    id: "in-beacon-docusign-text",
    channel: "text",
    fromName: "Owen Beacon",
    fromContact: "+1 617 555 0140",
    accountId: "acct-beacon",
    minutesAgo: 90,
    subject: null,
    body: "Hi — signed the DocuSign for the E&O package yesterday. When does coverage actually start? Also our biggest client wants a cert as soon as we're live.",
    callMissed: null,
    callDurationSec: null,
  },
];
