import type { Account, Policy, Underwriter } from "./types";

/**
 * Channel assignments (portal markets still keep emails for exceptions):
 *
 * Portal-first + service email retained:
 *   ISC, NEXT, Coterie, RT Specialty
 * Email-first (named UW):
 *   Kinsale, Hiscox, USLI, Markel, AmTrust, Thimble
 */
export const SEED_UNDERWRITERS: Underwriter[] = [
  {
    id: "uw-hiscox-1",
    name: "Jordan Hale",
    email: "jordan.hale@hiscox-uw.example",
    phone: "212-555-0142",
    portal: "https://partner.hiscox.com",
    carrier: "Hiscox",
    notes: "Primary Hiscox UW — email for endorsements & service",
    channelPrimary: "email",
    serviceEmail: null,
    channelNote: "Partner portal is for quoting; day-to-day service is email to the UW.",
  },
  {
    id: "uw-hiscox-2",
    name: "Priya Nair",
    email: "priya.nair@hiscox-uw.example",
    phone: "212-555-0188",
    portal: "https://partner.hiscox.com",
    carrier: "Hiscox",
    notes: "Backup — PL / Cyber",
    channelPrimary: "email",
    serviceEmail: null,
    channelNote: "Email first. Cancellations / address rewrites may need special handling.",
  },
  {
    id: "uw-coterie-1",
    name: "Coterie Partner Desk",
    email: "partners@coterie-desk.example",
    phone: "415-555-0190",
    portal: "https://partners.coterie.com",
    carrier: "Coterie",
    notes: "Blanket AI / WOS usually already on policy — verify before requesting",
    channelPrimary: "portal",
    serviceEmail: "partners@coterie-desk.example",
    channelNote:
      "Portal / self-serve first. Email exists for exceptions; billing changes often need customer ↔ Coterie.",
  },
  {
    id: "uw-kinsale-1",
    name: "Alex Rivera",
    email: "alex.rivera@kinsale-uw.example",
    phone: "804-555-0133",
    portal: "https://portal.kinsaleins.com",
    carrier: "Kinsale",
    notes: "High volume surplus GL / PL — email the UW on file",
    channelPrimary: "email",
    serviceEmail: null,
    channelNote: "Subjectivities and endorsement quotes go to the named UW by email.",
  },
  {
    id: "uw-kinsale-2",
    name: "Sam Ortiz",
    email: "sam.ortiz@kinsale-uw.example",
    phone: "804-555-0177",
    portal: "https://portal.kinsaleins.com",
    carrier: "Kinsale",
    notes: "Backup UW when Alex is out",
    channelPrimary: "email",
    serviceEmail: null,
    channelNote: "Email backup UW; portal is document reference.",
  },
  {
    id: "uw-amtrust-1",
    name: "Taylor Brooks",
    email: "taylor.brooks@amtrust-uw.example",
    phone: "800-555-0111",
    portal: "https://www.amtrustfinancial.com",
    carrier: "AmTrust",
    notes: "Workers' Comp IQ — watch bindability",
    channelPrimary: "email",
    serviceEmail: null,
    channelNote: "Email / UW path for WC service. Shop Byberg if AmTrust declines.",
  },
  {
    id: "uw-isc-1",
    name: "ISC Certs Desk",
    email: "certs@iscmga.com",
    phone: "877-555-0160",
    portal: "https://app.instantspecialty.com",
    carrier: "ISC",
    notes:
      "Session-based portal for IQ endorsements. Paper issues on Hadron Specialty / Sutton National / SiriusPoint America / Third Coast — the dec page governs.",
    channelPrimary: "hybrid",
    serviceEmail: "certs@iscmga.com",
    channelNote:
      "Portal for AI / name / address. 30-day notices & subjectivities: prepare the certificate and email it to certs@iscmga.com — ISC replies with an endorsement charge (about $100 in desk history) that must be approved before the endorsement issues.",
  },
  {
    id: "uw-next-1",
    name: "NEXT Portal Desk",
    email: "support@next-desk.example",
    phone: "888-555-0125",
    portal: "https://www.nextinsurance.com",
    carrier: "NEXT Insurance",
    notes: "Per-cert AI/WOS in portal (~$10); blanket needs a call",
    channelPrimary: "portal",
    serviceEmail: "support@next-desk.example",
    channelNote:
      "Portal for standard cert endorsements. Blanket WOS → insured calls NEXT. Support email for tickets.",
  },
  {
    id: "uw-rt-1",
    name: "RT Connect Desk",
    email: "support@rtspecialty-desk.example",
    phone: "312-555-0144",
    portal: "https://www.rtconnect.com",
    carrier: "RT Specialty",
    notes: "Wholesale submissions via RTConnect",
    channelPrimary: "portal",
    serviceEmail: "support@rtspecialty-desk.example",
    channelNote:
      "Portal first. Email/call support when RTConnect errors (effective date, DocuSign unlock).",
  },
  {
    id: "uw-usli-1",
    name: "Jamie Fox",
    email: "jamie.fox@usli-uw.example",
    phone: "888-555-0199",
    portal: "https://www.usli.com",
    carrier: "USLI",
    notes: "Email for endorsements; DocuSign only on bind packets",
    channelPrimary: "email",
    serviceEmail: null,
    channelNote:
      "Endorsements (AI, WOS, limits) = email the UW. DocuSign is for bind/apps — not for Additional Insured requests.",
  },
  {
    id: "uw-progressive-1",
    name: "Progressive Commercial Desk",
    email: "commercial@progressive-desk.example",
    phone: "800-555-0173",
    portal: "https://www.progressivecommercial.com",
    carrier: "Progressive",
    notes: "Business auto — portal for COIs and standard endorsements",
    channelPrimary: "portal",
    serviceEmail: "commercial@progressive-desk.example",
    channelNote:
      "Portal first (ForAgentsOnly). Email the commercial desk for exceptions.",
  },
  {
    id: "uw-markel-1",
    name: "Drew Patel",
    email: "drew.patel@markel-uw.example",
    phone: "804-555-0155",
    portal: "https://www.markel.com",
    carrier: "Markel",
    notes: "Daycare / specialty IQ",
    channelPrimary: "email",
    serviceEmail: null,
    channelNote: "Email the UW. Wholesale full-submission if IQ cannot place.",
  },
  {
    id: "uw-thimble-1",
    name: "Avery Kim",
    email: "avery.kim@thimble-uw.example",
    phone: "855-555-0102",
    portal: "https://www.thimble.com",
    carrier: "Thimble",
    notes: "Multi-location GL",
    channelPrimary: "email",
    serviceEmail: null,
    channelNote: "Email UW; portal for account reference.",
  },
];

// Account mailing addresses follow the same convention as the seed ticket
// holders: every street line sits on the US Census Bureau street grid
// (checked via the Census geocoder), so the certificate's INSURED box
// verification comes back clean rather than flagging invented streets.
const BASE_ACCOUNTS: Omit<Account, "status" | "paymentReceivedAt">[] = [
  {
    id: "acct-apex",
    name: "Apex Roofing LLC",
    dba: null,
    industry: "Roofing contractor",
    addressLine1: "2201 E 6th St",
    city: "Austin",
    state: "TX",
    zip: "78702",
    primaryUwId: "uw-kinsale-1",
    backupUwId: "uw-kinsale-2",
    notes: "Frequent AI / landlord COI requests — email Kinsale UW",
  },
  {
    id: "acct-bright",
    name: "Bright Path Daycare Inc",
    dba: "Bright Path Learning",
    industry: "Child care",
    addressLine1: "1240 Winchester Blvd",
    city: "San Jose",
    state: "CA",
    zip: "95128",
    primaryUwId: "uw-markel-1",
    backupUwId: "uw-rt-1",
    notes: "SAM separate; NEXT no longer available for daycares",
  },
  {
    id: "acct-harbor",
    name: "Harbor Medical Spa LLC",
    dba: null,
    industry: "Medical spa",
    addressLine1: "244 Madison Ave",
    city: "New York",
    state: "NY",
    zip: "10016",
    primaryUwId: "uw-hiscox-1",
    backupUwId: "uw-hiscox-2",
    notes: "PL + GL package; Hiscox email path",
  },
  {
    id: "acct-summit",
    name: "Summit Window & Door Co",
    dba: null,
    industry: "Window / door contractor",
    addressLine1: "2300 W 32nd Ave",
    city: "Denver",
    state: "CO",
    zip: "80211",
    primaryUwId: "uw-isc-1",
    backupUwId: "uw-rt-1",
    notes: "ISC portal for endorsements; email COI team for notices",
  },
  {
    id: "acct-northstar",
    name: "Northstar Logistics Inc",
    dba: "Northstar Freight",
    industry: "Truck / logistics",
    addressLine1: "2400 S Ashland Ave",
    city: "Chicago",
    state: "IL",
    zip: "60608",
    primaryUwId: "uw-amtrust-1",
    backupUwId: "uw-isc-1",
    notes:
      "WC + garage program on AmTrust — email the UW. Garage certs go out on ACORD 30, not 25.",
  },
  {
    id: "acct-greenleaf",
    name: "Greenleaf Landscaping LLC",
    dba: null,
    industry: "Landscaping",
    addressLine1: "5601 NW 72nd Ave",
    city: "Miami",
    state: "FL",
    zip: "33166",
    primaryUwId: "uw-coterie-1",
    backupUwId: null,
    notes: "Coterie — verify blanket AI on policy before any request",
  },
  {
    id: "acct-pixel",
    name: "PixelForge Studios LLC",
    dba: null,
    industry: "Software / tech",
    addressLine1: "1424 4th Ave",
    city: "Seattle",
    state: "WA",
    zip: "98101",
    primaryUwId: "uw-hiscox-2",
    backupUwId: "uw-hiscox-1",
    notes: "Tech E&O + Cyber — email Hiscox",
  },
  {
    id: "acct-metro",
    name: "Metro Towing Services Inc",
    dba: "Metro Tow",
    industry: "Towing / garage",
    addressLine1: "600 Communipaw Ave",
    city: "Jersey City",
    state: "NJ",
    zip: "07304",
    primaryUwId: "uw-isc-1",
    backupUwId: "uw-kinsale-1",
    notes: "Garage via ISC portal; Kinsale email backup",
  },
  {
    id: "acct-oakridge",
    name: "Oakridge Property Mgmt LLC",
    dba: null,
    industry: "Property management",
    addressLine1: "4150 N 12th St",
    city: "Phoenix",
    state: "AZ",
    zip: "85014",
    primaryUwId: "uw-next-1",
    backupUwId: "uw-coterie-1",
    notes: "NEXT portal for cert AI; call for blanket WOS",
  },
  {
    id: "acct-craft",
    name: "Craft & Barrel Catering LLC",
    dba: "Craft & Barrel",
    industry: "Catering / liquor",
    addressLine1: "2126 SE Division St",
    city: "Portland",
    state: "OR",
    zip: "97202",
    primaryUwId: "uw-usli-1",
    backupUwId: "uw-thimble-1",
    notes: "USLI — email endorsements; DocuSign only at bind",
  },
  {
    id: "acct-redwood",
    name: "Redwood Electric Inc",
    dba: "Redwood Electric",
    industry: "Electrical contractor",
    addressLine1: "2929 Fulton Ave",
    city: "Sacramento",
    state: "CA",
    zip: "95821",
    primaryUwId: "uw-kinsale-1",
    backupUwId: "uw-isc-1",
    notes:
      "GC AI + WOS stack is common; 30-day NOC required on most jobs — email Kinsale",
  },
  {
    id: "acct-lakeside",
    name: "Lakeside Veterinary Clinic PC",
    dba: "Lakeside Vet",
    industry: "Veterinary clinic",
    addressLine1: "3033 Excelsior Blvd",
    city: "Minneapolis",
    state: "MN",
    zip: "55416",
    primaryUwId: "uw-hiscox-1",
    backupUwId: "uw-usli-1",
    notes: "PL + GL; landlord AI requests weekly — Hiscox email",
  },
  {
    id: "acct-ironclad",
    name: "Ironclad Fabrication LLC",
    dba: null,
    industry: "Metal fabrication",
    addressLine1: "1200 W 3rd St",
    city: "Cleveland",
    state: "OH",
    zip: "44113",
    primaryUwId: "uw-amtrust-1",
    backupUwId: "uw-kinsale-2",
    notes: "WC AmTrust; GL Kinsale backup. Business-change notices when adding CNC line",
  },
  {
    id: "acct-cedar",
    name: "Cedar Grove Apartments LLC",
    dba: "Cedar Grove Residences",
    industry: "Multifamily real estate",
    addressLine1: "1280 W Peachtree St NW",
    city: "Atlanta",
    state: "GA",
    zip: "30309",
    primaryUwId: "uw-next-1",
    backupUwId: "uw-markel-1",
    notes: "NEXT portal for cert AI; lender 30-day NOC on renewals",
  },
  {
    id: "acct-ridgeline",
    name: "Ridgeline Automation LLC",
    dba: "Ridgeline Robotics",
    industry: "Industrial automation / robotics",
    addressLine1: "440 Burroughs St",
    city: "Detroit",
    state: "MI",
    zip: "48202",
    primaryUwId: "uw-kinsale-1",
    backupUwId: "uw-markel-1",
    notes:
      "Full program across four markets (GL + Umbrella Kinsale, Auto Progressive, WC AmTrust, Tech E&O/Cyber Markel) — the kitchen-sink COI account",
  },
  {
    // COI stress fixture — the "more policies than the sheet has rows" shape:
    // six policies across four carriers; E&O/Cyber/Liquor/second-GL lines
    // exceed the ACORD 25's printed sections and exercise description overflow.
    id: "acct-meridian",
    name: "Meridian Reach Marketing LLC",
    dba: "Meridian Reach",
    industry: "Marketing agency",
    addressLine1: "228 Park Ave S",
    city: "New York",
    state: "NY",
    zip: "10003",
    primaryUwId: "uw-kinsale-1",
    backupUwId: "uw-hiscox-1",
    notes:
      "Full multi-market program (GL + Umbrella + special-events GL Kinsale, Auto Progressive, WC AmTrust, Media E&O/Cyber Hiscox) — more coverage lines than an ACORD 25 has rows; overflow prints in Description Of Operations.",
  },
  {
    id: "acct-beacon",
    name: "Beacon IT Solutions LLC",
    dba: "Beacon IT",
    industry: "Managed IT / MSP",
    addressLine1: "745 Atlantic Ave",
    city: "Boston",
    state: "MA",
    zip: "02111",
    primaryUwId: "uw-hiscox-2",
    backupUwId: "uw-thimble-1",
    notes:
      "Technology errors & omissions plus cyber; client contracts often require additional insured and primary & non-contributory wording",
  },
];

export const SEED_POLICIES: Policy[] = [
  {
    id: "pol-apex-gl",
    accountId: "acct-apex",
    policyNumber: "KIN-GL-884201",
    carrier: "Kinsale",
    coverages: ["GL"],
    effectiveDate: "2026-01-15",
    expirationDate: "2027-01-15",
    premiumCents: 4_850_00,
    quoteInsuredName: "Apex Roofing LLC",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-apex-umb",
    accountId: "acct-apex",
    policyNumber: "KIN-XS-884202",
    carrier: "Kinsale",
    coverages: ["EXCESS_UMB"],
    effectiveDate: "2026-01-15",
    expirationDate: "2027-01-15",
    premiumCents: 1_200_00,
    quoteInsuredName: "Apex Roofing, L.L.C.",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-bright-gl",
    accountId: "acct-bright",
    policyNumber: "MKL-PKG-442910",
    carrier: "Markel",
    coverages: ["GL", "Prop"],
    effectiveDate: "2025-09-01",
    expirationDate: "2026-09-01",
    premiumCents: 6_400_00,
    quoteInsuredName: "Bright Path Daycare Inc",
    quoteCarrier: "Markel",
  },
  {
    id: "pol-harbor-pkg",
    accountId: "acct-harbor",
    policyNumber: "HSX-PL-229110",
    carrier: "Hiscox",
    coverages: ["GL", "PL"],
    effectiveDate: "2026-03-01",
    expirationDate: "2027-03-01",
    premiumCents: 3_275_00,
    quoteInsuredName: "Harbor Medical Spa LLC",
    quoteCarrier: "Hiscox",
  },
  {
    id: "pol-harbor-cyber",
    accountId: "acct-harbor",
    policyNumber: "HSX-CY-229111",
    carrier: "Hiscox",
    coverages: ["CL"],
    effectiveDate: "2026-03-01",
    expirationDate: "2027-03-01",
    premiumCents: 890_00,
    quoteInsuredName: "Harbor Medical Spa LLC",
    quoteCarrier: "Hiscox",
  },
  {
    id: "pol-summit-gl",
    accountId: "acct-summit",
    policyNumber: "ISC-GL-551002",
    carrier: "ISC",
    coverages: ["GL"],
    effectiveDate: "2026-02-10",
    expirationDate: "2027-02-10",
    premiumCents: 2_140_00,
    quoteInsuredName: "Summit Window & Door Co",
    quoteCarrier: "ISC",
    // Dec page: ISC (MGA) paper written on Sutton National — NAIC 25798
    issuingCarrier: "Sutton National Insurance Company",
  },
  {
    id: "pol-northstar-wc",
    accountId: "acct-northstar",
    policyNumber: "AMT-WC-778301",
    carrier: "AmTrust",
    coverages: ["WC"],
    effectiveDate: "2026-01-01",
    expirationDate: "2027-01-01",
    premiumCents: 12_600_00,
    quoteInsuredName: "Northstar Logistics Inc",
    quoteCarrier: "AmTrust",
  },
  {
    id: "pol-northstar-gar",
    accountId: "acct-northstar",
    policyNumber: "AMT-GAR-778302",
    carrier: "AmTrust",
    coverages: ["Garage", "GK", "HNOA"],
    effectiveDate: "2026-01-01",
    expirationDate: "2027-01-01",
    premiumCents: 5_900_00,
    // Intentional human-error demo: wrong quote name uploaded
    quoteInsuredName: "North Star Freight LLC",
    quoteCarrier: "AmTrust",
  },
  {
    id: "pol-greenleaf-bop",
    accountId: "acct-greenleaf",
    policyNumber: "COT-BOP-331450",
    carrier: "Coterie",
    coverages: ["BOP", "GL"],
    effectiveDate: "2025-11-15",
    expirationDate: "2026-11-15",
    premiumCents: 1_680_00,
    quoteInsuredName: "Greenleaf Landscaping LLC",
    quoteCarrier: "Coterie",
  },
  {
    id: "pol-pixel-eo",
    accountId: "acct-pixel",
    policyNumber: "HSX-EO-990120",
    carrier: "Hiscox",
    coverages: ["TECH_EO", "CL"],
    effectiveDate: "2026-04-01",
    expirationDate: "2027-04-01",
    premiumCents: 2_450_00,
    quoteInsuredName: "PixelForge Studios LLC",
    quoteCarrier: "Hiscox",
  },
  {
    id: "pol-metro-gar",
    accountId: "acct-metro",
    policyNumber: "ISC-GAR-112233",
    carrier: "ISC",
    coverages: ["Garage", "CA"],
    effectiveDate: "2026-05-01",
    expirationDate: "2027-05-01",
    premiumCents: 7_200_00,
    quoteInsuredName: "Metro Towing Services Inc",
    quoteCarrier: "ISC",
    // Dec page: ISC (MGA) paper written on Third Coast — NAIC 10713
    issuingCarrier: "Third Coast Insurance Company",
  },
  {
    id: "pol-oakridge-gl",
    accountId: "acct-oakridge",
    policyNumber: "NXT-GL-667788",
    carrier: "NEXT Insurance",
    coverages: ["GL"],
    effectiveDate: "2025-12-01",
    expirationDate: "2026-12-01",
    premiumCents: 1_150_00,
    quoteInsuredName: "Oakridge Property Mgmt LLC",
    quoteCarrier: "NEXT Insurance",
  },
  {
    id: "pol-craft-liq",
    accountId: "acct-craft",
    policyNumber: "USLI-LL-445566",
    carrier: "USLI",
    coverages: ["GL", "Liquor"],
    effectiveDate: "2026-06-01",
    expirationDate: "2027-06-01",
    premiumCents: 3_980_00,
    // Intentional: wrong carrier on quote upload
    quoteInsuredName: "Craft & Barrel Catering LLC",
    quoteCarrier: "Hiscox",
  },
  {
    id: "pol-redwood-gl",
    accountId: "acct-redwood",
    policyNumber: "KIN-GL-910447",
    carrier: "Kinsale",
    coverages: ["GL"],
    effectiveDate: "2026-02-01",
    expirationDate: "2027-02-01",
    premiumCents: 5_620_00,
    quoteInsuredName: "Redwood Electric Inc",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-redwood-wc",
    accountId: "acct-redwood",
    policyNumber: "AMT-WC-910448",
    carrier: "AmTrust",
    coverages: ["WC"],
    effectiveDate: "2026-02-01",
    expirationDate: "2027-02-01",
    premiumCents: 18_400_00,
    quoteInsuredName: "Redwood Electric Inc",
    quoteCarrier: "AmTrust",
  },
  {
    id: "pol-lakeside-pkg",
    accountId: "acct-lakeside",
    policyNumber: "HSX-PKG-338821",
    carrier: "Hiscox",
    coverages: ["GL", "PL"],
    effectiveDate: "2025-10-15",
    expirationDate: "2026-10-15",
    premiumCents: 4_110_00,
    quoteInsuredName: "Lakeside Veterinary Clinic PC",
    quoteCarrier: "Hiscox",
  },
  {
    id: "pol-ironclad-wc",
    accountId: "acct-ironclad",
    policyNumber: "AMT-WC-552119",
    carrier: "AmTrust",
    coverages: ["WC"],
    effectiveDate: "2026-01-01",
    expirationDate: "2027-01-01",
    premiumCents: 22_850_00,
    quoteInsuredName: "Ironclad Fabrication LLC",
    quoteCarrier: "AmTrust",
  },
  {
    id: "pol-ironclad-gl",
    accountId: "acct-ironclad",
    policyNumber: "KIN-GL-552120",
    carrier: "Kinsale",
    coverages: ["GL", "ProdL"],
    effectiveDate: "2026-01-01",
    expirationDate: "2027-01-01",
    premiumCents: 7_340_00,
    quoteInsuredName: "Ironclad Fabrication LLC",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-cedar-gl",
    accountId: "acct-cedar",
    policyNumber: "NXT-GL-774455",
    carrier: "NEXT Insurance",
    coverages: ["GL"],
    effectiveDate: "2025-08-01",
    expirationDate: "2026-08-01",
    premiumCents: 2_890_00,
    quoteInsuredName: "Cedar Grove Apartments LLC",
    quoteCarrier: "NEXT Insurance",
  },
  {
    id: "pol-cedar-prop",
    accountId: "acct-cedar",
    policyNumber: "MKL-CP-774456",
    carrier: "Markel",
    coverages: ["Prop"],
    effectiveDate: "2025-08-01",
    expirationDate: "2026-08-01",
    premiumCents: 41_200_00,
    quoteInsuredName: "Cedar Grove Apartments LLC",
    quoteCarrier: "Markel",
  },
  {
    id: "pol-ridgeline-gl",
    accountId: "acct-ridgeline",
    policyNumber: "KIN-GL-773100",
    carrier: "Kinsale",
    coverages: ["GL"],
    effectiveDate: "2026-04-01",
    expirationDate: "2027-04-01",
    premiumCents: 6_950_00,
    quoteInsuredName: "Ridgeline Automation LLC",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-ridgeline-auto",
    accountId: "acct-ridgeline",
    policyNumber: "PRG-CA-449213",
    carrier: "Progressive",
    coverages: ["CA"],
    effectiveDate: "2026-04-01",
    expirationDate: "2027-04-01",
    premiumCents: 8_750_00,
    quoteInsuredName: "Ridgeline Automation LLC",
    quoteCarrier: "Progressive",
  },
  {
    id: "pol-ridgeline-umb",
    accountId: "acct-ridgeline",
    policyNumber: "KIN-XS-773101",
    carrier: "Kinsale",
    coverages: ["EXCESS_UMB"],
    effectiveDate: "2026-04-01",
    expirationDate: "2027-04-01",
    premiumCents: 2_100_00,
    quoteInsuredName: "Ridgeline Automation LLC",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-ridgeline-wc",
    accountId: "acct-ridgeline",
    policyNumber: "AMT-WC-773102",
    carrier: "AmTrust",
    coverages: ["WC"],
    effectiveDate: "2026-04-01",
    expirationDate: "2027-04-01",
    premiumCents: 15_300_00,
    quoteInsuredName: "Ridgeline Automation LLC",
    quoteCarrier: "AmTrust",
  },
  {
    id: "pol-ridgeline-eo",
    accountId: "acct-ridgeline",
    policyNumber: "MKL-TE-773103",
    carrier: "Markel",
    coverages: ["TECH_EO", "CL"],
    effectiveDate: "2026-04-01",
    expirationDate: "2027-04-01",
    premiumCents: 4_400_00,
    quoteInsuredName: "Ridgeline Automation LLC",
    quoteCarrier: "Markel",
  },
  // ——— Meridian Reach Marketing — COI overflow stress fixture ———
  {
    id: "pol-meridian-gl",
    accountId: "acct-meridian",
    policyNumber: "KIN-GL-902311",
    carrier: "Kinsale",
    coverages: ["GL"],
    effectiveDate: "2026-05-01",
    expirationDate: "2027-05-01",
    premiumCents: 5_240_00,
    quoteInsuredName: "Meridian Reach Marketing LLC",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-meridian-auto",
    accountId: "acct-meridian",
    policyNumber: "PRG-CA-556710",
    carrier: "Progressive",
    coverages: ["CA"],
    effectiveDate: "2026-03-15",
    expirationDate: "2027-03-15",
    premiumCents: 3_410_00,
    quoteInsuredName: "Meridian Reach Marketing LLC",
    quoteCarrier: "Progressive",
  },
  {
    id: "pol-meridian-umb",
    accountId: "acct-meridian",
    policyNumber: "KIN-XS-902312",
    carrier: "Kinsale",
    coverages: ["EXCESS_UMB"],
    effectiveDate: "2026-05-01",
    expirationDate: "2027-05-01",
    premiumCents: 1_980_00,
    quoteInsuredName: "Meridian Reach Marketing LLC",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-meridian-wc",
    accountId: "acct-meridian",
    policyNumber: "AMT-WC-902313",
    carrier: "AmTrust",
    coverages: ["WC"],
    effectiveDate: "2026-01-01",
    expirationDate: "2027-01-01",
    premiumCents: 9_820_00,
    quoteInsuredName: "Meridian Reach Marketing LLC",
    quoteCarrier: "AmTrust",
  },
  {
    id: "pol-meridian-eo",
    accountId: "acct-meridian",
    policyNumber: "HSX-ME-902314",
    carrier: "Hiscox",
    coverages: ["PL", "CL"],
    // Renewal-window edge: in force today, expires within weeks.
    effectiveDate: "2025-08-15",
    expirationDate: "2026-08-15",
    premiumCents: 4_130_00,
    quoteInsuredName: "Meridian Reach Marketing LLC",
    quoteCarrier: "Hiscox",
  },
  {
    id: "pol-meridian-events",
    accountId: "acct-meridian",
    policyNumber: "KIN-EV-902319",
    carrier: "Kinsale",
    coverages: ["GL", "Liquor"],
    // Temporal edge: bound but not yet effective (brand-activation event).
    effectiveDate: "2026-09-10",
    expirationDate: "2026-09-14",
    premiumCents: 760_00,
    quoteInsuredName: "Meridian Reach Marketing LLC",
    quoteCarrier: "Kinsale",
  },
  {
    id: "pol-beacon-eo",
    accountId: "acct-beacon",
    policyNumber: "HSX-EO-661203",
    carrier: "Hiscox",
    coverages: ["TECH_EO", "CL"],
    effectiveDate: "2026-03-15",
    expirationDate: "2027-03-15",
    premiumCents: 3_650_00,
    quoteInsuredName: "Beacon IT Solutions LLC",
    quoteCarrier: "Hiscox",
  },
];

/**
 * New business — quoted/bound but payment not yet received.
 * Payment is what flips an account into active service.
 */
const PRE_BIND_ACCOUNT_IDS = new Set(["acct-beacon", "acct-bright"]);

/** Seed convention: payment landed at inception of the earliest policy. */
function earliestEffectiveDate(accountId: string): string | null {
  const dates = SEED_POLICIES.filter((p) => p.accountId === accountId)
    .map((p) => p.effectiveDate)
    .sort();
  return dates[0] ?? null;
}

export const SEED_ACCOUNTS: Account[] = BASE_ACCOUNTS.map((a) =>
  PRE_BIND_ACCOUNT_IDS.has(a.id)
    ? { ...a, status: "pre_bind" as const, paymentReceivedAt: null }
    : {
        ...a,
        status: "active" as const,
        paymentReceivedAt: earliestEffectiveDate(a.id),
      },
);
