import { AUTO_APPROVE_THRESHOLD_CENTS } from "../types";
import { channelLabel, type ChannelRoute } from "./channels";
import { getRequestType } from "../catalog";
import { formatMoney } from "../format";
import { MODEL_PURPOSE_LABELS, type ModelCall } from "../model";
import { getEmailTemplate, type EmailTemplateId } from "./templates";
import { normalizeCompanyName, type VerifyResult } from "./verify";
import { ticketSourceLabel } from "../tickets/tickets";
import type {
  AccountDetail,
  Operator,
  Policy,
  Ticket,
  Underwriter,
} from "../types";

/**
 * Why the machine did what it did.
 *
 * Every decision here is already made somewhere else — verify.ts picks the
 * underwriter, channels.ts picks the route, filenames.ts renames the files.
 * This module does not re-decide anything. It reads the same result objects
 * the send path acts on and writes down the reasoning, so a sent email can
 * always answer "why this desk, why this channel, what did you check."
 */

export type StepVerdict = "ok" | "warn" | "block" | "info";

/**
 * A rule step can be re-derived from the inputs. A model step cannot — the
 * prompt and the raw response are the only record of what happened, so they
 * are carried on the step itself rather than summarized away.
 */
export type StepSource = "rule" | "model";

export interface ModelStepDetail {
  model: string;
  system: string | null;
  prompt: string;
  response: string;
  temperature: number | null;
  confidence: number | null;
  promptTokens: number | null;
  responseTokens: number | null;
  latencyMs: number;
  accepted: boolean;
  overrideNote: string | null;
}

export interface TraceStep {
  id: string;
  label: string;
  /** The rule in plain words — what the system was deciding */
  rule: string;
  /** What it looked at, in the order it looked */
  inputs: { label: string; value: string }[];
  /** What it concluded */
  outcome: string;
  verdict: StepVerdict;
  /** Absent on steps written before model calls existed — treat as a rule */
  source?: StepSource;
  model?: ModelStepDetail;
}

export type TraceKind =
  | "send"
  | "auto_send"
  | "reply"
  | "approval"
  | "client_terms"
  | "certificate";

export type TraceAuthor = "ai" | "operator" | "market";

export interface DecisionTrace {
  id: string;
  ticketId: string;
  threadId: string | null;
  messageId: string | null;
  kind: TraceKind;
  author: TraceAuthor;
  headline: string;
  summary: string;
  steps: TraceStep[];
  createdAt: string;
}

export const TRACE_KIND_LABELS: Record<TraceKind, string> = {
  send: "Email Sent",
  auto_send: "Auto-Sent",
  reply: "Market Replied",
  approval: "Premium Decision",
  client_terms: "Terms Relayed",
  certificate: "Certificate Decision",
};

export const TRACE_AUTHOR_LABELS: Record<TraceAuthor, string> = {
  ai: "AI",
  operator: "Operator",
  market: "Market",
};

export const VERDICT_STYLES: Record<StepVerdict, string> = {
  ok: "bg-emerald-50 text-emerald-800 border-emerald-200",
  warn: "bg-amber-50 text-amber-900 border-amber-200",
  block: "bg-rose-50 text-rose-900 border-rose-200",
  info: "bg-slate-50 text-slate-700 border-slate-200",
};

export const VERDICT_DOTS: Record<StepVerdict, string> = {
  ok: "bg-emerald-500",
  warn: "bg-amber-500",
  block: "bg-rose-500",
  info: "bg-slate-400",
};

export function traceKindLabel(kind: string): string {
  return TRACE_KIND_LABELS[kind as TraceKind] ?? kind;
}

/** The worst thing the chain found — what the row badge should show. */
export function worstVerdict(steps: TraceStep[]): StepVerdict {
  if (steps.some((s) => s.verdict === "block")) return "block";
  if (steps.some((s) => s.verdict === "warn")) return "warn";
  if (steps.some((s) => s.verdict === "ok")) return "ok";
  return "info";
}

export function hasModelStep(steps: TraceStep[]): boolean {
  return steps.some((s) => s.source === "model");
}

/**
 * One step per model call, carrying the prompt and the raw response.
 *
 * A generation the operator threw away is recorded as loudly as one that
 * shipped — an overridden draft is the signal that the model is wrong about
 * something, and averaging it out of the record hides exactly that.
 */
export function buildModelSteps(calls: ModelCall[]): TraceStep[] {
  return calls.map((call) => ({
    id: `model-${call.id}`,
    label: MODEL_PURPOSE_LABELS[call.purpose],
    rule: `Generated by a model, not a rule. Nothing here is derivable from the inputs — the prompt and the response below are the whole record.${call.accepted ? "" : " This generation did not go out."}`,
    inputs: [
      { label: "Model", value: call.model },
      { label: "Asked For", value: call.intent },
      ...(call.temperature != null
        ? [{ label: "Temperature", value: String(call.temperature) }]
        : []),
      {
        label: "Confidence",
        value:
          call.confidence != null
            ? `${Math.round(call.confidence * 100)}%`
            : "Not reported by the provider",
      },
      {
        label: "Tokens",
        value:
          call.promptTokens != null && call.responseTokens != null
            ? `${call.promptTokens} in / ${call.responseTokens} out`
            : "Not reported",
      },
      { label: "Latency", value: `${call.latencyMs}ms` },
      ...(call.overrideNote
        ? [{ label: "Overridden", value: call.overrideNote }]
        : []),
    ],
    outcome: call.accepted
      ? "Used in what went out"
      : "Discarded — a human replaced it before sending",
    verdict: call.accepted ? "warn" : "info",
    source: "model",
    model: {
      model: call.model,
      system: call.system,
      prompt: call.prompt,
      response: call.response,
      temperature: call.temperature,
      confidence: call.confidence,
      promptTokens: call.promptTokens,
      responseTokens: call.responseTokens,
      latencyMs: call.latencyMs,
      accepted: call.accepted,
      overrideNote: call.overrideNote,
    },
  }));
}

export interface SendTraceInput {
  ticket: Ticket;
  account: AccountDetail;
  policy: Policy;
  /** Every policy on the ticket, so the selection step can show what it passed over */
  candidatePolicies: Policy[];
  verify: VerifyResult;
  underwriter: Underwriter;
  route: ChannelRoute;
  templateId: EmailTemplateId;
  operator: Operator | null;
  attachments: { name: string; originalName?: string | null }[];
  /** Operator rewrote the AI draft before sending */
  edited: boolean;
  /** Operator ticked through warn-level findings */
  ackWarnings: boolean;
  /** Sent by the streak unlock rather than a human click */
  auto: boolean;
  /** Which touch this was on the ticket — anything past 1 wanted a reason */
  touch: number;
  loopReasonLabel: string | null;
  /** Every model call made while producing this email, from one session */
  modelCalls?: ModelCall[];
}

/** Model calls that read the request belong next to the request. */
const READING_PURPOSES = new Set(["wording_read", "holder_extract"]);

/** The full chain behind one outbound market email. */
export function buildSendSteps(input: SendTraceInput): TraceStep[] {
  const {
    ticket,
    account,
    policy,
    verify,
    underwriter,
    route,
    operator,
  } = input;
  const req = getRequestType(ticket.requestType);
  const steps: TraceStep[] = [];
  const calls = input.modelCalls ?? [];
  const readingCalls = calls.filter((c) => READING_PURPOSES.has(c.purpose));
  const writingCalls = calls.filter((c) => !READING_PURPOSES.has(c.purpose));

  steps.push({
    id: "request",
    label: "Request Read",
    rule: "Intake tells us who asked and what they owe the holder.",
    inputs: [
      { label: "Source", value: ticketSourceLabel(ticket.source) },
      {
        label: "Asked By",
        value: ticket.requestedByEmail
          ? `${ticket.requestedBy} (${ticket.requestedByEmail})`
          : ticket.requestedBy,
      },
      { label: "Subject", value: ticket.subject },
      { label: "Holder", value: ticket.holderName ?? "None given" },
      {
        label: "Wording",
        value: ticket.wording.trim() || "None given",
      },
    ],
    outcome: `${req.label} for ${account.name}`,
    verdict: "info",
  });

  steps.push(...buildModelSteps(readingCalls));

  const others = input.candidatePolicies.filter((p) => p.id !== policy.id);
  steps.push({
    id: "policy",
    label: "Policy Selected",
    rule: "A ticket can span policies. The request goes to the one that carries the coverage.",
    inputs: [
      {
        label: "On The Ticket",
        value:
          input.candidatePolicies
            .map((p) => `${p.carrier} ${p.policyNumber}`)
            .join(" · ") || "None",
      },
      { label: "Chosen", value: `${policy.carrier} ${policy.policyNumber}` },
      {
        label: "Passed Over",
        value: others.length
          ? others.map((p) => `${p.carrier} ${p.policyNumber}`).join(" · ")
          : "Nothing — single policy on this ticket",
      },
    ],
    outcome: `${policy.carrier} ${policy.policyNumber}`,
    verdict: others.length ? "warn" : "ok",
  });

  const rerouted = verify.matchSource !== "primary";
  steps.push({
    id: "underwriter",
    label: "Underwriter Match",
    rule: "Match the desk to the policy's carrier — account primary first, then backup, then the carrier desk. Never blind-send to the primary.",
    inputs: [
      { label: "Policy Carrier", value: policy.carrier },
      {
        label: "Account Primary",
        value: `${account.primaryUw.name} (${account.primaryUw.carrier})`,
      },
      {
        label: "Account Backup",
        value: account.backupUw
          ? `${account.backupUw.name} (${account.backupUw.carrier})`
          : "None on file",
      },
      { label: "Rule That Matched", value: matchSourceLabel(verify.matchSource) },
    ],
    outcome: `${underwriter.name} — ${underwriter.carrier}`,
    verdict: rerouted ? "warn" : "ok",
  });

  const quoteName = policy.quoteInsuredName;
  steps.push({
    id: "quote-name",
    label: "Quote Cross-Check",
    rule: "Quotes get uploaded to the wrong account. Compare the named insured on the quote against this account before asking the market for anything.",
    inputs: [
      { label: "Quote Named Insured", value: quoteName ?? "Not on file" },
      { label: "Account Legal Name", value: account.name },
      { label: "Account DBA", value: account.dba ?? "None" },
      {
        label: "Compared As",
        value: quoteName
          ? `“${normalizeCompanyName(quoteName)}” vs “${normalizeCompanyName(account.name)}”`
          : "Nothing to compare",
      },
      {
        label: "Quote Carrier",
        value: policy.quoteCarrier ?? "Not on file",
      },
    ],
    outcome: quoteMatchOutcome(verify, quoteName),
    verdict: quoteMatchVerdict(verify, quoteName),
  });

  steps.push({
    id: "route",
    label: "Channel Route",
    rule: "Carrier and request type decide the channel. Endorsement requests never need a signature packet — that is bind paperwork.",
    inputs: [
      { label: "Carrier", value: policy.carrier },
      { label: "Request Type", value: req.label },
      { label: "Portal On File", value: underwriter.portal ?? "None" },
      {
        label: "Address Used",
        value: route.email ?? underwriter.email,
      },
      { label: "Carrier Rule", value: route.instruction },
    ],
    outcome: `${channelLabel(route.primary)}${route.sendEmail ? "" : " — logged as a task, not an email"}`,
    verdict: "info",
  });

  steps.push(...buildModelSteps(writingCalls));

  steps.push({
    id: "compose",
    label: "Body Composed",
    rule: "The template comes from the operator's profile and the signature is stamped at render — never typed by hand.",
    inputs: [
      { label: "Template", value: getEmailTemplate(input.templateId).label },
      {
        label: "Written By",
        value: writingCalls.length
          ? `${writingCalls.length} model call${writingCalls.length === 1 ? "" : "s"} — see the steps above`
          : "Deterministic template — no model touched this body",
      },
      {
        label: "Signed As",
        value: operator
          ? `${operator.displayName}, ${operator.title}`
          : "No operator on file",
      },
      {
        label: "Operator Edits",
        value: input.edited
          ? "Rewrote the draft before sending"
          : "Sent the draft as generated",
      },
      {
        label: "Edit Reason",
        value: input.loopReasonLabel ?? "Not applicable",
      },
    ],
    outcome: input.edited
      ? "Human-edited body"
      : writingCalls.length
        ? "Model draft sent unchanged"
        : "Template draft sent unchanged",
    verdict: input.edited ? "warn" : "ok",
  });

  if (input.attachments.length > 0) {
    steps.push({
      id: "attachments",
      label: "Attachments Named",
      rule: "One convention leaves this desk: {Entity} - {Kind}.{ext}. Nobody downstream should have to open a file to know what it is.",
      inputs: input.attachments.map((a) => ({
        label: a.originalName && a.originalName !== a.name ? a.originalName : "As Dropped",
        value: a.name,
      })),
      outcome: `${input.attachments.length} file${input.attachments.length === 1 ? "" : "s"} attached`,
      verdict: "info",
    });
  }

  const findings = input.verify.issues;
  const flagged = findings.some((i) => i.severity === "warn");
  steps.push({
    id: "gate",
    label: "Send Gate",
    rule: "Blocks stop the send outright. Warnings need a human to tick them off. Only then does the button arm.",
    inputs:
      findings.length > 0
        ? findings.map((i) => ({
            label: `${i.severity.toUpperCase()} — ${i.title}`,
            value: i.detail,
          }))
        : [{ label: "Findings", value: "Nothing flagged" }],
    outcome: input.auto
      ? "Auto-sent on an earned streak — no human click"
      : flagged && input.ackWarnings
        ? "Operator acknowledged the warnings and sent"
        : "Clean — sent on one click",
    verdict: flagged ? "warn" : "ok",
  });

  if (input.touch > 1) {
    steps.push({
      id: "loop",
      label: "Repeat Contact",
      rule: "Any outbound after the first on a ticket is a loop, and a loop has to name its reason. That tag is the list of things to go kill.",
      inputs: [
        { label: "Touch Number", value: String(input.touch) },
        {
          label: "Reason Given",
          value: input.loopReasonLabel ?? "Untagged",
        },
      ],
      outcome: `Touch ${input.touch} on this ticket`,
      verdict: "warn",
    });
  }

  return steps;
}

function matchSourceLabel(source: VerifyResult["matchSource"]): string {
  switch (source) {
    case "primary":
      return "Account primary matched the policy carrier";
    case "backup":
      return "Primary was a different market — account backup matched";
    case "carrier_desk":
      return "Neither account contact matched — routed to the carrier desk";
    case "none":
      return "No desk on file for this carrier";
  }
}

function quoteMatchOutcome(
  verify: VerifyResult,
  quoteName: string | null,
): string {
  if (verify.issues.some((i) => i.id === "quote-name-mismatch")) {
    return "Named insured does not match this account";
  }
  if (verify.issues.some((i) => i.id === "quote-carrier-mismatch")) {
    return "Quote carrier does not match the policy";
  }
  if (!quoteName) return "No quote named insured on file to check against";
  return "Quote matches the account";
}

function quoteMatchVerdict(
  verify: VerifyResult,
  quoteName: string | null,
): StepVerdict {
  if (
    verify.issues.some(
      (i) => i.id === "quote-name-mismatch" || i.id === "quote-carrier-mismatch",
    )
  ) {
    return "block";
  }
  return quoteName ? "ok" : "warn";
}

/** How the market's answer turns into the next move, and on whose authority. */
export function buildReplySteps(input: {
  underwriter: Underwriter;
  premiumImpactCents: number;
  autoApproved: boolean;
  modelCalls?: ModelCall[];
}): TraceStep[] {
  const zero = input.premiumImpactCents === 0;
  return [
    ...buildModelSteps(input.modelCalls ?? []),
    {
      id: "reply-read",
      label: "Reply Read",
      rule: "The premium in the market's answer decides the whole downstream path.",
      inputs: [
        { label: "From", value: `${input.underwriter.name} — ${input.underwriter.carrier}` },
        {
          label: "Premium Impact",
          value: zero ? "No additional premium" : formatMoney(input.premiumImpactCents),
        },
      ],
      outcome: zero
        ? "No charge — the certificate is ours to issue"
        : `Market wants ${formatMoney(input.premiumImpactCents)}`,
      verdict: zero ? "ok" : "warn",
    },
    {
      id: "authority",
      label: "Authority Check",
      rule: `Agent authority stops at ${formatMoney(AUTO_APPROVE_THRESHOLD_CENTS)}. At or under, the agent proceeds. Over, a human decides and the client sees terms.`,
      inputs: [
        { label: "Quoted", value: formatMoney(input.premiumImpactCents) },
        { label: "Authority Limit", value: formatMoney(AUTO_APPROVE_THRESHOLD_CENTS) },
      ],
      outcome: input.autoApproved
        ? "Within authority — agent proceeded without asking"
        : "Over authority — parked for a human and a client relay",
      verdict: input.autoApproved ? "ok" : "warn",
    },
  ];
}

/** Why a certificate was issued or refused, against the forms actually on the policy. */
export function buildCertificateSteps(input: {
  decision: "issued" | "rejected";
  summary: string;
  policy: Policy;
  modelCalls?: ModelCall[];
}): TraceStep[] {
  const calls = input.modelCalls ?? [];
  return [
    {
      id: "cert-source",
      label: "Data Source",
      rule: "The certificate fills from the coverage tab on the policy — never from a customer's emailed document, and never from a model reading a PDF.",
      inputs: [
        { label: "Policy", value: `${input.policy.carrier} ${input.policy.policyNumber}` },
        { label: "Filled From", value: "Policy coverage record" },
        {
          label: "Model Involvement",
          value: calls.length
            ? `${calls.length} model call${calls.length === 1 ? "" : "s"} read the uploaded document — the limits still came from the policy`
            : "None — every field came from structured policy data",
        },
      ],
      outcome: "Structured fill from the policy of record",
      verdict: "ok",
    },
    ...buildModelSteps(calls),
    {
      id: "cert-verdict",
      label: "Verification Verdict",
      rule: "Reject anything the policy does not back — coverage that is not there, limits above the policy, or description wording with nothing behind it.",
      inputs: [{ label: "Findings", value: input.summary || "None recorded" }],
      outcome:
        input.decision === "issued"
          ? "Every line on the certificate is backed by the policy"
          : "Refused — the certificate claimed something the policy does not carry",
      verdict: input.decision === "issued" ? "ok" : "block",
    },
  ];
}
