/**
 * Observed issue vocabulary — a captured snapshot of every open issue type in
 * both stores, taken from the live `service.open_issues_by_stage` pack on
 * 2026-08-15 (5,214 open rows: 2,690 spine, 2,524 legacy).
 *
 * This exists as a coverage fixture. The normalizer has to have a canonical
 * name for everything in here, and the check harness fails if any value falls
 * through to `unknown`. Re-capture it when the vocabulary moves; the failure it
 * produces is the point, because silent drift is how these two stores got out
 * of step in the first place.
 */

import type { RawIssueCount } from "./normalize";

export const OBSERVED_ISSUE_VOCABULARY: RawIssueCount[] = [
  { sourceStore: "legacy", issueType: "CANCELLATION_ALERT", openCount: 490 },
  { sourceStore: "legacy", issueType: "GENERAL_SERVICE_REQUEST", openCount: 447 },
  { sourceStore: "legacy", issueType: "ENDORSEMENT_REQUEST", openCount: 298 },
  { sourceStore: "legacy", issueType: "MISC_SUBJECTIVITY", openCount: 210 },
  { sourceStore: "legacy", issueType: "policy_delivery", openCount: 140 },
  { sourceStore: "legacy", issueType: "COLLECT_SUBJECTIVITIES", openCount: 110 },
  { sourceStore: "legacy", issueType: "PAYMENT_FAILURE", openCount: 106 },
  { sourceStore: "legacy", issueType: "POLICY_DELIVERY", openCount: 78 },
  { sourceStore: "legacy", issueType: "COI_REQUEST", openCount: 78 },
  { sourceStore: "legacy", issueType: "PUSH_TO_UW", openCount: 62 },
  { sourceStore: "legacy", issueType: "IQ_BIND_AND_ISSUE", openCount: 58 },
  { sourceStore: "legacy", issueType: "DOCUSIGN_BUILD", openCount: 56 },
  { sourceStore: "legacy", issueType: "IQ_COI_SEND", openCount: 40 },
  { sourceStore: "legacy", issueType: "PFA_UPLOAD", openCount: 36 },
  { sourceStore: "legacy", issueType: "FINAL_PAYMENT_PENDING", openCount: 35 },
  { sourceStore: "legacy", issueType: "UNDERWRITING", openCount: 31 },
  { sourceStore: "legacy", issueType: "ADDRESS_CHANGE", openCount: 25 },
  { sourceStore: "legacy", issueType: "BROKER_COI_SEND", openCount: 20 },
  { sourceStore: "legacy", issueType: "INSURED_SIGN_PENDING", openCount: 20 },
  { sourceStore: "legacy", issueType: "BINDER_INVOICE_PENDING", openCount: 20 },
  { sourceStore: "legacy", issueType: "onboarding", openCount: 14 },
  { sourceStore: "legacy", issueType: "INSPECTION_REQUIREMENT", openCount: 14 },
  { sourceStore: "legacy", issueType: "CERTIFICATE_HOLDER_CHANGE", openCount: 11 },
  { sourceStore: "legacy", issueType: "BIND_POLICY", openCount: 11 },
  { sourceStore: "legacy", issueType: "COI_SEND", openCount: 10 },
  { sourceStore: "legacy", issueType: "SUBMISSION_FOLLOW_UP", openCount: 9 },
  { sourceStore: "legacy", issueType: "GENERAL_INQUIRY", openCount: 9 },
  { sourceStore: "legacy", issueType: "PAYMENT_METHOD_CHANGE", openCount: 8 },
  { sourceStore: "legacy", issueType: "CERTIFICATE_OF_INSURANCE", openCount: 7 },
  { sourceStore: "legacy", issueType: "CLAIMS_ALERT", openCount: 7 },
  { sourceStore: "legacy", issueType: "DOCUMENT_CORRECTION", openCount: 5 },
  { sourceStore: "legacy", issueType: "POLICY_DOCS_PENDING", openCount: 5 },
  { sourceStore: "legacy", issueType: "PLACEMENT_FOLLOW_UP", openCount: 5 },
  { sourceStore: "legacy", issueType: "DOCUSIGN_SEND", openCount: 5 },
  { sourceStore: "legacy", issueType: "PRODUCER_SIGN_PENDING", openCount: 4 },
  { sourceStore: "legacy", issueType: "CANCEL_NON_PAY", openCount: 3 },
  { sourceStore: "legacy", issueType: "MISSING_DOCUMENT", openCount: 3 },
  { sourceStore: "legacy", issueType: "SUBJECTIVITY_MONITORING", openCount: 3 },
  { sourceStore: "legacy", issueType: "DOCUSIGN", openCount: 3 },
  { sourceStore: "legacy", issueType: "DocuSign", openCount: 2 },
  { sourceStore: "legacy", issueType: "DOCUSIGN_COMPLETED_REVIEW", openCount: 2 },
  { sourceStore: "legacy", issueType: "DOCUMENTS", openCount: 2 },
  { sourceStore: "legacy", issueType: "DOCUSIGN_AND_SUBJECTIVITIES", openCount: 2 },
  { sourceStore: "legacy", issueType: "docusign_chase", openCount: 2 },
  { sourceStore: "legacy", issueType: "SUBJECTIVITY_CARRIER_NEGOTIATION", openCount: 2 },
  { sourceStore: "legacy", issueType: "SUBJECTIVITY_SENSITIVE", openCount: 2 },
  { sourceStore: "legacy", issueType: "APPLICATION_COMPLETION", openCount: 1 },
  { sourceStore: "legacy", issueType: "APPLICATION_RECEIVED", openCount: 1 },
  { sourceStore: "legacy", issueType: "BILLING_PAYMENT", openCount: 1 },
  { sourceStore: "legacy", issueType: "BIND_REQUEST", openCount: 1 },
  { sourceStore: "legacy", issueType: "CANCELLATION", openCount: 1 },
  { sourceStore: "legacy", issueType: "DOCUSIGN_SIGNED", openCount: 1 },
  { sourceStore: "legacy", issueType: "DOCUSIGN_VOIDED", openCount: 1 },
  { sourceStore: "legacy", issueType: "ENDORSEMENT", openCount: 1 },
  { sourceStore: "legacy", issueType: "ENDORSEMENT_CANCELLATION", openCount: 1 },
  { sourceStore: "legacy", issueType: "GENERAL_REQUEST", openCount: 1 },
  { sourceStore: "legacy", issueType: "PLACEMENT_UW_FOLLOW_UP", openCount: 1 },
  { sourceStore: "legacy", issueType: "PORTAL_ACCESS", openCount: 1 },
  { sourceStore: "legacy", issueType: "UNDERWRITER_FOLLOW_UP", openCount: 1 },
  { sourceStore: "legacy", issueType: "UW_FOLLOW_UP", openCount: 1 },
  { sourceStore: "spine", issueType: "general_request", openCount: 574 },
  { sourceStore: "spine", issueType: "cancellation", openCount: 561 },
  { sourceStore: "spine", issueType: "endorsement", openCount: 344 },
  { sourceStore: "spine", issueType: "onboarding", openCount: 309 },
  { sourceStore: "spine", issueType: "policy_delivery", openCount: 290 },
  { sourceStore: "spine", issueType: "coi_request", openCount: 250 },
  { sourceStore: "spine", issueType: "payment_failure", openCount: 162 },
  { sourceStore: "spine", issueType: "subjectivity", openCount: 111 },
  { sourceStore: "spine", issueType: "inspection", openCount: 43 },
  { sourceStore: "spine", issueType: "portal_access", openCount: 27 },
  { sourceStore: "spine", issueType: "pfa", openCount: 10 },
  { sourceStore: "spine", issueType: "claim", openCount: 8 },
  { sourceStore: "spine", issueType: "refund", openCount: 1 },
];
